name: hive_repo
description: >-
  Repositories classes to standardize access to hive boxes for user defined types
version: 1.3.0
homepage: https://github.com/msiviero/hive_repo

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  hive: ^2.0.0
  quiver: ^3.0.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
